# Introduction {#sec:introduction}

At the 1971 meeting of the American Economic Association (AEA), it was declared that "economics is not exclusively a man's field". Alongside this declaration, a commitment was made to "a positive program to eliminate sex discrimination among economists" and the Committee on the Status of Women in the Economics Profession (CSWEP) was established [@Cherrier2017]. Similar organisations and committees have since emerged elsewhere, including the International Association for Feminist Economics (established in 1992), the UK's Royal Economic Society (established in 1996) and the European Economic Association Women's Committee (established in 2003).

A goal of many of these organisations has been to regularly report on the status of women in economics in their respective countries or regions. To fulfil this responsibility, the UK's Royal Economic Society (RES) surveyed UK departments throughout the period between 1996--2016. In this paper, we append this survey data to administrative data on all staff and students at UK higher education institutes supplied by the Higher Education Statistical Agency (HESA). Our combined dataset provides a comprehensive and intersectional overview of how diversity in economics---from the undergraduate through to the professorship levels---has evolved in the UK over the past quarter century.

While progress has been made, we find that women are still under-represented in UK academic economics at both ends of the pipeline---at the undergraduate level and among academics. In 2018, women represented 32 percent of economics undergraduate students (compared with 27 percent in 1996) and 26 percent of academic economists (compared with no more than 18 percent in 1996) [@Mumford1997;@Tenreyro2017]. Women are, however, better represented among graduate students (around half in 2018 were women compared with 30 percent in 1996), largely thanks to an inflow of international students studying on taught master's courses.

Among students in general, we find that the representation of women is poor among UK nationals, and our data suggest that this gender gap has become worse rather than better since 2002. The proportion of UK-domiciled economics undergraduates who are women has fallen from 31 percent in 2002 to 27 percent in 2018; at the master's degree level, the proportion has fallen from 37 percent in 2002 to 31 percent in 2018. At both levels of study, women are better represented among economics students from ethnic minorities; however, the reverse is true at the Ph.D. level. For undergraduates in 2018, the percentage of women is highest among Asian (31 percent) and Black students (33 percent) and lowest among white students (25 percent). Women's representation at the master's degree level was 5 percentage points higher among Black and minority ethnicity (BME) students than it was among non-BME students. For Ph.D. students, however, women's representation was 10 percentage points higher among non-BME students than it was among BME students.

Among academic economists, we find that women are worse off on almost every dimension considered. They are substantially more likely to be employed at lower academic ranks---for example, in 2018, they made up 33 percent of lecturers, 27 percent of senior lecturers/readers (a category which consists of academics who rank somewhere between the lecturer and professor level) and a mere 15 percent of professors (the highest-ranking academic position). And while the overall growth in women's representation is upward, progress in closing the gender gap stalled around 2012, particularly among lecturers and professors. Compared to men, women are also more likely to be employed in fixed-term---and generally lower status---teaching-only and research-only positions.

When we look at the intersection of gender and race amongst academics, we find further reasons to be concerned. Only 8 percent of standard academic contracts were held by Black and minority ethnicity women in 2018---compared to 17 percent for men---and strikingly, at no point between 2012--2018 was a Black female professor of economics employed anywhere in the UK. Finally, the percentage of economics professors with Asian ethnicity who are women has in fact been falling (from 22 percent in 2012 to 16 percent in 2018).

Our paper adds to a growing body of research on the gender gap in economics. The gap is visible in a number of countries and across multiple dimensions. Initial research focussed on women's presence amongst academic economists, a tradition we continue here, albeit with a much more intersectional focus.^[See also @Blackaby2000 and @Advani2020.] Recent research has also explored women's presence in publications and textbooks [@Moon2022;@Hengel2022;@Stevenson2018]---which, by comparison with academic posts, suggests even greater under-representation---as well as seminars [@Doleac2021]. In addition to women's representation, the literature has also considered the degree to which women progress in the discipline relative to men, examining gender gaps in pay, tenure and promotion.^[This includes, but is not restricted to @Auriol2022, @Blackaby2005, @Ceci2014, @Chevalier2021, @CostaDias2021, @Gamage2020, @Ginther2004, @Kahn2020, @Lundberg2019, @Mumford2019, @Sarsons2021 and @Ward2001.]

While this body of research identifies "missing women" in economics, a complementary literature in the history of economic thought points to a parallel problem of "hidden women". The contributions made by numerous female economists over the long span of the discipline---some of whom were side-lined or neglected by mainstream economics and therefore often found in non-economics departments---are now, as a result, being highlighted afresh [see, *e.g.*, @Folbre1988;@Kuiper2022;@Madden1993;@Madden2018]. While the present paper does not investigate female economists' presence in non-economics departments, we hope the issue can be examined more closely in future research.

In what follows, [Section @sec:setting] discusses the institutional context behind UK academia. In [Section @sec:data], we describe our data. [Section @sec:findings] presents our findings. In [Section @sec:discussion] we compare our findings for the UK to other countries and consider some possible causes for the stagnation and retreat experienced in the UK and elsewhere. [Section @sec:conclusion] concludes.
