# UK academia {#sec:setting}

The UK is home to around 170 universities. The oldest English universities are Oxford and Cambridge, which were established in the 12th and 13th centuries, respectively. The first universities in Scotland were St Andrews, Glasgow, Aberdeen and Edinburgh, all founded in the 15th and 16th centuries. Most other well-known UK universities date from the 19th and early 20th centuries, with the notable exception of around 40 former polytechnic teaching institutions (many originally founded in the 1960s) that were granted university status in 1992.

UK universities are legally independent entities. Academic matters are usually overseen by a senate composed of a university's academic staff; non-academic affairs---including finances, estate management and human resources---are generally governed by a council of lay members. Most universities' revenue is a mix of tuition fees and government spending. The latter is generally tied to student numbers, subjects taught and the quality and volume of research; the former is capped for most UK students but can run as high as £60,000 per year for international students [see, *e.g.*, @Cambridge2022].

There are four academic ranks in UK universities. "Lecturers" are traditionally entry-level positions analogous to assistant professors in the United States; the next rank, "senior lecturer", is roughly equivalent to an associate professor. The third rank, "reader", is awarded to distinguished senior academics who have not yet attained the status of "professor", which is traditionally reserved only for the most senior academics and is roughly equivalent to chaired professorships in the United States.^["Reader" is equivalent a U.S. non-chaired professor. Some UK universities have eliminated the "reader" title entirely, converted it to "professor" or combined it with "senior lecturer" into a single rank (sometimes titled "associate professor").]

Most UK academic appointments at the level of lecturer and above combine responsibilities for both teaching and research and are made on a permanent/open-ended basis. Before 1987, academic posts were "tenured" following a three-year probationary period, meaning that tenured staff could not be made redundant under any circumstance (although they could still be dismissed for reasons related to competence or conduct). Tenure was abolished, however, with the Education Reform Act of 1988;^[The Act technically awards universities' councils the power to make academic staff redundant. Unlike other universities in the UK, most academic staff at Oxford and Cambridge are members of these governing bodies and are therefore especially unlikely to approve any redundancy plans put before them. As a result, academic staff at both universities are, *de facto*, afforded far stronger employment protections compared to academics employed by other institutions. For further information and discussion, see @Otsuka2019.] as a result, academic staff in UK universities are no longer legally protected against redundancy, and at most universities, they now have the same statutory employment rights as other workers in the UK.^[Some UK universities continue to apply a three-year probationary period to new academic staff; however, the abolishment of tenure meant that dismissals due to failing probation are no longer regulated by the 1971 Academic and Related Salaries settlement between the University Authorities Panel and the Association of University Teachers [@AUT1974]. As a result, probationary staff members in the UK are afforded similar statutory employment protections as non-probationary staff members with the same length of service.]