# Data {#sec:data}

To analyse the gender composition of UK academic economists, we combine data from two sources: data collected by the Royal Economic Society (RES) for the period 1996--2016 and data from the UK's Higher Education Statistics Agency (HESA) for the period 2012--2018.

The RES data are from a historic survey of the members on its Conferences of Heads of University Departments of Economics (CHUDE). The survey was conducted bi-annually between 1996--2016 and provide a panel dataset of departments' gender composition by rank and year. For further discussion of the history and methodology of the survey, and for why data collection ceased in 2016, see @Bateman2021.

HESA staff data are reported by universities and cover all individuals on a contract of employment with a publicly funded higher education provider in the UK during a given academic year (1 August to 31 July). The data we analyse stratify staff numbers in terms of full-time equivalents (FTE), where FTE indicates the proportion of a full-time year being undertaken within a given stratification. For the purposes of this analysis, we restrict staff data to include only academic staff members who engage in teaching and/or research activities in the field of economics. To identify economists, we select staff members employed by an economics department or business school and whose primary or secondary academic discipline is economics. To ensure they are engaged in academic teaching and/or research activities, we additionally exclude people not on academic contracts or on atypical contracts as well as staff with an unknown academic rank, classified as professional or administrative staff and routine or simple task providers. Since our primary aim is to analyse gender differences in career academic economists, we also exclude teaching and research assistants unless otherwise mentioned.

HESA data for students include information on all students enrolled in a course with a level of instruction above three according to Ofqual's Qualifications and Credit Framework (or an earlier equivalent). The data we analyse break down student counts in terms of "instance", where instance refers to a particular student-course combination.^[Since students can take multiple courses, a single student may correspond to more than one instance in the data. Moreover, universities can report up to three subject descriptors for each course with the proportion of time the course allocates to the subject. For example, students enrolled on a BSc programme that devotes equal time to philosophy and economics would appear as two instances in the HESA data, each weighted by 0.5.] We restrict the data to men and women enrolled full-time on a standard economics degree programme. As a result, we exclude part-time and other non-full-time students and those on non-first-degree undergraduate programmes or non-master's/Ph.D. postgraduate programmes. Given the purpose of this exercise is to analyse the representation of women in economics, our focus is on those who declare their gender as either male or female.^[We hope less restrictive, non-binary classifications will be explored in future research.]

Published research using HESA data must comply with its rounding and suppression strategy. To adhere to this strategy, all counts of people are rounded to the nearest multiple of five and percentages are suppressed if they are based on fewer than 22.5 individuals. Because these rules are applied post-calculation (*e.g.*, after summing FTEs), numbers may not always perfectly add up (*e.g.*, the counts of male and female students may not precisely sum to the total number of students in a category). Further details of HESA's rounding and suppression strategy can be found on its website.