# Discussion {#sec:discussion}

According to our data, women comprise only 26 percent of academic economists in the UK. Unfortunately, representation is not radically higher elsewhere: women are also 26 percent of worldwide economists [@RePEc2022] and 26 percent of economists at Ph.D. granting institutions in the United States [@Chevalier2021]. According to @Auriol2022, women are a slightly higher fraction (33 percent) of academic economists in continental Europe, although there is substantial heterogeneity across countries.

Our evidence also suggests that female economists in UK academia are promoted more slowly than male economists. Again, the trend is similar in most other countries [see, *e.g.*, @Auriol2022; @Ceci2014; @Chevalier2021; @Ginther2014; @Jacobsen2006b; @Lundberg2019]. In the United States, CSWEP tracks cohorts of Ph.D. students through the academic pipeline; while women tend to achieve assistant professorships at the same rate as their male peers, this is not the case at higher academic ranks [@Chevalier2021;@Lundberg2019]. Moreover, @Ginther2004 found that only 47 percent of female economists were tenured 10 years post-Ph.D., compared with 68 percent of male economists.

We further find that growth in women's representation may be starting to slow, a long-term trend consistent with data from the United States [@Lundberg2019] and apparent in other metrics of gender inequality. Progress on women's representation in top economics journals has been particularly glacial, *e.g.*, between 1986--2015, there was zero growth in the fraction of exclusively female-authored papers published in "top-five" economics journals [@Moon2022].^[The "top-five" journals in economics are the *American Economic Review*, *Econometrica*, *Journal of Political Economy*, *Quarterly Journal of Economics* and *Review of Economic Studies*.]  Even though the gender pay gap declined across Britain between 1999--2016, there was "no notable fall in the unexplained (conditional) gender pay gap for UK academic economists" during the same period [@Mumford2019, p. 103]; at the London School of Economics, it actually increased [@Bandiera2016].

In contrast, industry and government appear to have had more success at creating work environments that are attractive to female economists. In the UK Treasury, 38 percent of economic staff are women [@CabinetOffice2020]. At the Bank of England, 32 percent of senior staff and 46 percent of their new graduate intake are women [@BoE2020]. At the Institute for Fiscal Studies, 52 percent of in-house researchers are female [@IFS2021] and at NIESR, 45 percent are [@NIESR2021a; @NIESR2021b].

Why are women under-represented in academic economics and why has progress been so slow? As is well known, women face more obstacles on career progression---including gendered societal expectations regarding unpaid care---and the way academia responds to these obstacles (relative to other career options) may increase the opportunity cost of remaining. For example, @Goldin2014 argues that many women prefer flexible work and are willing to sacrifice pay and promotion to achieve it. And although evidence does not suggest that flexibility is important to women early in their careers, it does suggest that they develop a revealed preference for it by the time they reach their 30s [@Ferriman2009; @Lubinski2006; @Ceci2014]. As a result, greater scope for part-time employment would likely encourage more women to remain in academia and may explain why industry and government have had more success attracting and retaining them.^[A related barrier may be the fact that "work devotion" is a particular feature of academic life, with academics being "especially responsive to the demands of work, because the success and rewards of their work are central to how they define themselves" [@Fox2021, p. 3]. @Goldin2014 argues that the gender gap could be reduced considerably if employers "did not have an incentive to disproportionately reward individuals who labored long hours" [@Goldin2014, p. 1091]. Increasing demands in terms of international travel---for conferences, collaborations and jobs---are a related feature of academic life [@Canibano2016]. This can offer opportunities to women, but it can also "raise barriers". @Ferber1979 noted that three-quarters of women in the USA with Ph.D.s are partnered with someone who also has a Ph.D. (whereas only a third of men with Ph.D.s are partnered with women with Ph.D.s), creating greater potential conflict in the careers of women. They further noted that women Ph.D.s are more likely to move for their partner's career (than vice versa), and that the more they do so, the lower are their own chances of being employed. Further research is needed on the degree to which this remains the case.]

Another issue stalling women in UK academia is discrimination related to pay and promotion. @Bandiera2016 found that women earned 11 percent less than men at the London School of Economics, controlling for age, tenure and research productivity. @Mumford2019 surveyed academic economists across the entire UK and found a gender pay gap of 9.1 log percentage points after conditioning on similar variables. @McManus2018 analysed submissions for the UK's 2014 Research Excellence Framework and found that economics departments were about 10 percent less likely to submit research by female lecturers compared to observably equivalent male lecturers. In the United States, women take longer and are less likely to achieve tenure in economics, conditional on publications, citations and children [@Ginther2014], and articles women co-author with men count less toward their promotion compared to articles men co-author with other men [@Sarsons2021].

Evidence also suggests that female-authored articles are held to higher standards, potentially further limiting women's academic careers. Papers authored by women are 6.8 percent less likely to be accepted to conferences [@Hospido2021] and spend longer in peer review [@Hengel2022; @Alexander2021]. Once published, they are more readable and receive more citations [@Card2020;@Hengel2022;@Moon2022;@Grossbard2021]. Consistent with these findings, a controlled laboratory experiment found that "female authors appeared to be seen as less competent than males, in that subjects (being incentivized to give their best judgement) less often believed that their papers have been published" [@Krawczyk2016, p. 326].

Women economists also face more hostile working conditions compared to men. @Wu2020 applied text mining and machine learning methods to posts on Economics Job Market Rumors (EJMR), a popular, anonymous online forum of economists. She found that posts about women were more focused on personal characteristics compared to posts about men, which tended to emphasise professional accomplishments. During seminars, female economists are also asked more questions, and a higher proportion of those questions are perceived as unfair, hostile or patronising by audience members [@Dupas2021].^[Growing concern about the treatment of women recently led the American Economic Association to survey their members about the professional climate in economics. The survey found that women were significantly more likely than men to say that they had personally experienced discrimination or unfair treatment with respect to pay, publishing decisions, invitations to conferences and networks, course evaluations and service obligations [@AEA2019]. Compared to men, women were also far less likely to agree with the statement "I am satisfied with the overall climate within the field of economics". In the UK, a similar climate survey was subsequently conducted by the Royal Economic Society. It found that 52 percent of respondents agreed that the climate in economics is aggressive and 32 percent that it is discriminatory [@RES2020]. Only one in three agreed or strongly agreed that it is inclusive.]

Economics' lack of diversity may arguably affect the way it is studied and its ability to attract a more diverse group of scholars going forward [@Bateman2019]. The majority of introductory economics courses still do not reference gender [@Asarta2020], and the profession appears to have a particular "resistance to any kind of feminist theory or feminist activism" (Nancy Folbre, quoted in @OrozcoEspinel2022, p. 1186). Moreover, evidence suggests that topics of specialisation that disproportionately attract women or minorities are seen as lower status [@Key2019; @Fortin2021; @Zacchia2021].^[Relatedly, public goods disproportionately provided by women---including mentoring and diversity activities---are often undervalued in hiring and promotion decisions [see, *e.g.*, @Jacobsen2006a].] As a result, some may choose to eschew economics altogether (missing women) while others search for a scholarly home in non-economics departments (hidden women).