# Conclusion {#sec:conclusion}

In this paper, we examine women's representation in UK economics, from the undergraduate level through to the professorship, over the period 1996--2018. We find that women now represent around a quarter of academic economists---33 percent of lecturers, 27 percent of senior lecturers/readers and 15 percent of professors---up from 18 percent in 1996.

But while progress has clearly been made, we also identify a number of ways in which women's representation may be stagnating and even retreating. To begin with, the academic pipeline is shrinking. Among UK nationals, the female proportion of economics students has fallen over the past two decades. In 2002, 31 percent of UK nationals studying economics at undergraduate level were women; by 2018, this had fallen to 27 percent. Once the intersection of gender and race are considered, the findings suggest even more cause for concern. While the proportion of women amongst minority groups is higher than it is among white students at the undergraduate level, the reverse is true for Ph.D. students: women's representation in 2018 was 10 percentage points higher among non-BME Ph.D. students than it was among BME Ph.D. students. At the other end of the pipeline, there is a particular absence of non-white women. We could not find a single Black female professor of economics in the UK in the period up to 2018, and the proportion of women among professors with Asian ethnicity fell from 22 percent in 2012 to 16 percent in 2018.

Our findings for the UK are not unlike those elsewhere in the world and add to a growing literature documenting academic gender gaps. In addition to a lack of representation, women are paid less and are less likely to achieve tenure or be promoted compared to their male peers. They are also given a harder time in seminar presentations and are substantially less likely to publish in top economics journals.

One question we have not explored is whether women are "missing" from the economics profession entirely or just "hidden" from view. Given the historic purpose of the RES's data collection efforts, we have narrowly defined "economists" to include only academics studying or working in economics departments or business schools. As a result, we have, sadly, overlooked female economists in departments excluded by this definition---*e.g.*, history, political science or sociology. We hope future research will more carefully investigate whether female economists are "missing" from the academy entirely, or instead simply "hiding" in economics-adjacent disciplines.