---
title: "The gender gap in UK academic economics 1996--2018: progress, stagnation, and retreat"
authors:
  - name: Victoria Bateman
    affiliation: University of Cambridge
    email: vb295@cam.ac.uk
  - name: Erin Hengel
    affiliation: London School of Economics
    email: erin.hengel@gmail.com
abstract: |
  This paper reports on women’s representation in UK economics over the last quarter century. While progress has been made---for example, in 2018, women were 32 percent of economics undergraduate students (compared with 27 percent in 1996) and 26 percent of academic economists (compared with 18 percent in 1996)---women are still under-represented in UK academia, and our data suggest several areas of stagnation and retreat. First, the percentage of female UK nationals studying economics is low and falling over time. Second, among academic economists, we find that women are substantially more likely to be employed at lower academic ranks and in fixed-term—and generally lower status—teaching-only and research-only positions. Third, the representation of women is especially low among ethnic minorities studying for an economics Ph.D. And finally, between 2012–2018 the percentage of economics professors with Asian ethnicity who are women has been falling, and at no point during this period was a Black female professor of economics employed anywhere in the UK.
acknowledgements: |
  All errors are our own. We are especially indebted to Almudena Sevilla for supporting the project, two anonymous referees and Danula Kankanam Gamage and Xianyue Liu for excellent research assistance. We also thank current and former members of the Royal Economic Society Women's Committee—and in particular Heather Joshi, Karen Mumford, Denise Osborn, Almudena Sevilla and Sarah Smith—for extensive comments and feedback on an earlier draft. Parts of this paper were originally released as a report to the Royal Economic Society's Women's Committee, titled “The Gender Imbalance in UK Economics”, co-authored with Danula Kankanam Gamage and Xianyue Liu. The data copyright is held by the Royal Economic Society and the Higher Education Statistics Agency (HESA). Neither HESA Limited nor HESA Services Limited are responsible for any inferences or conclusions derived by the authors from the data or other information supplied by HESA Limited or HESA Services Limited.
date: "`r format(Sys.time(), '%B %Y')`"
keywords:
jel:
output:
  bookdown::pdf_document2:
    template: 0-templates/paper-biber.tex
    latex_engine: xelatex
    citation_package: biblatex
    keep_tex: no
    pandoc_args: ["--filter", "pandoc-crossref"]
bibliography: 0-bib/references.bib
link-citations: true
always_allow_html: true
knit: (function (...) { source('0-code/myknit.R'); myknit(...) })
---

```{r setup, include=FALSE, cache=FALSE}
# Set up document (ggplot defaults, knitr hooks, etc.)
source('0-code/setup.R')

# Read in data
source('0-code/data.R')
```

\clearpage

```{r child = '1-introduction.Rmd'}
```

```{r child = '2-setting.Rmd'}
```

```{r child = '3-data.Rmd'}
```

```{r child = '4-findings.Rmd'}
```

```{r child = '5-discussion.Rmd'}
```

```{r child = '6-conclusion.Rmd'}
```

\newpage

# References {-}

\printbibliography[heading=none]

<!-- \bibliography{0-bib/references} -->

\newpage

# (APPENDIX) Appendix {-}

\setcounter{figure}{0}
\setcounter{table}{0}
\setcounter{equation}{0}
\counterwithin*{table}{section}
\counterwithin*{figure}{section}
\renewcommand{\thetable}{\thesection.\arabic{table}}
\renewcommand{\thefigure}{\thesection.\arabic{figure}}
\appendixpage

```{r child = 'A-definitions.Rmd'}
```

\newpage

```{r child = 'B-staff.Rmd'}
```

\newpage

```{r child = 'C-nationality.Rmd'}
```

\newpage

```{r child = 'D-school.Rmd'}
```
